import { Category } from '@/core/models/category';
import { Injectable } from '@angular/core';
import { delay, Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class CategoryService {

  findAll(): Observable<Category[]> {
    return of([
      { name: "Alimentos", slug: "alimentos", color: "#FF5733" },
      { name: "Tecnologia", slug: "tecnologia", color: "#33FF57" },
      { name: "Saúde", slug: "saude", color: "#5733FF" },
      { name: "Educação", slug: "educacao", color: "#FF33A6" },
      { name: "Entretenimento", slug: "entretenimento", color: "#A633FF" },
      { name: "Esportes", slug: "esportes", color: "#FFBF33" },
      { name: "Viagens", slug: "viagens", color: "#33FFF2" },
      { name: "Moda", slug: "moda", color: "#F233FF" },
      { name: "Automóveis", slug: "automoveis", color: "#33A6FF" },
      { name: "Negócios", slug: "negocios", color: "#FF3366" },
      { name: "Imóveis", slug: "imoveis", color: "#FF8333" },
      { name: "Música", slug: "musica", color: "#33FF99" },
      { name: "Cultura", slug: "cultura", color: "#FFCC33" },
      { name: "Política", slug: "politica", color: "#33D9FF" },
      { name: "Arte", slug: "arte", color: "#B933FF" },
      { name: "Ciência", slug: "ciencia", color: "#FF6633" },
      { name: "Jogos", slug: "jogos", color: "#33FFCC" },
      { name: "Literatura", slug: "literatura", color: "#CC33FF" },
      { name: "Culinária", slug: "culinaria", color: "#FF3333" },
      { name: "Bem-estar", slug: "bem-estar", color: "#FF3366" },
      { name: "Astronomia", slug: "astronomia", color: "#33FF80" },
      { name: "Fotografia", slug: "fotografia", color: "#80FF33" },
      { name: "História", slug: "historia", color: "#FF8033" },
      { name: "Comédia", slug: "comedia", color: "#FF3380" },
      { name: "Documentários", slug: "documentarios", color: "#80FF33" },
      { name: "Política Internacional", slug: "politica-internacional", color: "#33FF33" },
      { name: "Literatura Fantástica", slug: "literatura-fantastica", color: "#9933FF" },
      { name: "Esportes Radicais", slug: "esportes-radiciais", color: "#3366FF" },
      { name: "Games Online", slug: "games-online", color: "#33CCFF" },
      { name: "Meditação", slug: "meditacao", color: "#FF99CC" },
      { name: "Psicologia", slug: "psicologia", color: "#FF6699" },
      { name: "Religião", slug: "religiao", color: "#CC99FF" },
      { name: "Negócios Digitais", slug: "negocios-digitais", color: "#FF9933" },
      { name: "Design Gráfico", slug: "design-grafico", color: "#33FF99" },
      { name: "Turismo", slug: "turismo", color: "#33CC99" },
      { name: "Arte Contemporânea", slug: "arte-contemporanea", color: "#CCFF33" },
      { name: "Ciência Política", slug: "ciencia-politica", color: "#FF6600" },
      { name: "Saúde Mental", slug: "saude-mental", color: "#FF3366" },
      { name: "Automação", slug: "automacao", color: "#FF00FF" },
      { name: "Espiritualidade", slug: "espiritualidade", color: "#99FF33" },
      { name: "Empreendedorismo", slug: "empreendedorismo", color: "#66FF33" },
      { name: "Marketing Digital", slug: "marketing-digital", color: "#FF9966" },
      { name: "Startups", slug: "startups", color: "#66FF99" },
      { name: "Fotografia de Natureza", slug: "fotografia-de-natureza", color: "#33FF66" },
      { name: "Carreira", slug: "carreira", color: "#FF6699" },
      { name: "Design de Moda", slug: "design-de-moda", color: "#FF0033" },
      { name: "Inovação", slug: "inovacao", color: "#33FFCC" },
      { name: "Artesanato", slug: "artesanato", color: "#FF9933" },
      { name: "Marketing Pessoal", slug: "marketing-pessoal", color: "#CCFF66" },
      { name: "Filosofia", slug: "filosofia", color: "#FF3399" },
      { name: "Cinema", slug: "cinema", color: "#33FF99" },
      { name: "Teatro", slug: "teatro", color: "#33FF00" },
      { name: "Arquitetura", slug: "arquitetura", color: "#FF3300" },
      { name: "Linguística", slug: "linguistica", color: "#FF6666" },
      { name: "Tecnologia Verde", slug: "tecnologia-verde", color: "#FF9933" },
      { name: "Biotecnologia", slug: "biotecnologia", color: "#6600FF" },
      { name: "História da Arte", slug: "historia-da-arte", color: "#FF5733" },
      { name: "Teoria da Conspiração", slug: "teoria-da-conspiracao", color: "#FF3380" },
      { name: "Tradições Culturais", slug: "tradicoes-culturais", color: "#33CCFF" },
      { name: "Antropologia", slug: "antropologia", color: "#FF66FF" },
      { name: "Sociologia", slug: "sociologia", color: "#33FF80" },
      { name: "Arquivos e Memória", slug: "arquivos-e-memoria", color: "#FF3399" },
      { name: "Novos Negócios", slug: "novos-negocios", color: "#33FF99" },
      { name: "Eventos", slug: "eventos", color: "#FF9933" },
      { name: "Recursos Humanos", slug: "recursos-humanos", color: "#6699FF" },
      { name: "Cidadania", slug: "cidadania", color: "#FF6633" },
      { name: "Cultura Digital", slug: "cultura-digital", color: "#FF3399" },
      { name: "Literatura Brasileira", slug: "literatura-brasileira", color: "#FFCC00" },
      { name: "Filmes Clássicos", slug: "filmes-classicos", color: "#33FF00" },
      { name: "Jogos de Tabuleiro", slug: "jogos-de-tabuleiro", color: "#6600FF" },
      { name: "Jornalismo", slug: "jornalismo", color: "#FF0066" },
      { name: "Engenharia", slug: "engenharia", color: "#33A6FF" },
      { name: "Educação Física", slug: "educacao-fisica", color: "#FF3300" },
      { name: "Gestão", slug: "gestao", color: "#FF5733" },
      { name: "Finanças Pessoais", slug: "financas-pessoais", color: "#99FF33" },
      { name: "Tendências de Mercado", slug: "tendencias-de-mercado", color: "#33FF99" },
      { name: "Sustentabilidade", slug: "sustentabilidade", color: "#00FF99" },
      { name: "Literatura Internacional", slug: "literatura-internacional", color: "#FF6633" },
      { name: "Astrologia", slug: "astrologia", color: "#FF33FF" },
      { name: "Educação Infantil", slug: "educacao-infantil", color: "#6699FF" },
      { name: "Inovação Social", slug: "inovacao-social", color: "#33FF66" },
      { name: "Ecologia", slug: "ecologia", color: "#99FF66" },
      { name: "Cidadania Digital", slug: "cidadania-digital", color: "#00CCFF" },
      { name: "Jornalismo Investigativo", slug: "jornalismo-investigativo", color: "#99CCFF" },
      { name: "Desenvolvimento Pessoal", slug: "desenvolvimento-pessoal", color: "#FF6600" },
      { name: "Cervejas Artesanais", slug: "cervejas-artesanais", color: "#FF3366" },
      { name: "Meio Ambiente", slug: "meio-ambiente", color: "#00FF00" },
      { name: "Publicidade", slug: "publicidade", color: "#33CC33" },
      { name: "Arquivos Históricos", slug: "arquivos-historicos", color: "#00FF66" },
      { name: "Tradição e Cultura", slug: "tradicao-e-cultura", color: "#6666FF" },
      { name: "Ciência da Computação", slug: "ciencia-da-computacao", color: "#FF33A6" },
      { name: "Consultoria Empresarial", slug: "consultoria-empresarial", color: "#FF8000" },
      { name: "Fotografia Artística", slug: "fotografia-artistica", color: "#00FFFF" },
      { name: "E-commerce", slug: "e-commerce", color: "#FF9900" },
      { name: "Gestão de Pessoas", slug: "gestao-de-pessoas", color: "#33FF33" },
      { name: "Futebol", slug: "futebol", color: "#CC3366" },
      { name: "Relações Internacionais", slug: "relacoes-internacionais", color: "#FF66CC" },
      { name: "Mobilidade Urbana", slug: "mobilidade-urbana", color: "#99FF00" },
      { name: "Cultura Pop", slug: "cultura-pop", color: "#FFCC66" },
      { name: "Design de Interiores", slug: "design-de-interiores", color: "#33FF80" },
      { name: "Paternidade", slug: "paternidade", color: "#FF3380" },
      { name: "Empregabilidade", slug: "empregabilidade", color: "#FF66FF" }
    ]).pipe(delay(300))
  }
}
